# Copyright (c) 2021 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ $comp := .Values.components.server -}}
{{- $this := dict "root" . "gp" $.Values "comp" $comp -}}

{{- define "stable-image-full" -}}
{{- $ := .root -}}
{{- $gp := .gp -}}
{{- $comp := .comp -}}
{{ template "gitpod.comp.imageRepo" . }}:{{ $comp.stableVersion }}
{{- end -}}

{{- define "insider-image-full" -}}
{{- $ := .root -}}
{{- $gp := .gp -}}
{{- $comp := .comp -}}
{{ template "gitpod.comp.imageRepo" . }}:{{- $comp.insidersVersion | default (include "gitpod.comp.version" .) -}}
{{- end -}}

# For backwards compability - remove me soon
{{- define "ide-images-aliases"}}
{{- $ := .root -}}
{{- $gp := .gp -}}
code: {{ (include "stable-image-full" (dict "root" $ "gp" $gp "comp" $gp.components.workspace.codeImage)) }}
code-latest: {{ (include "insider-image-full" (dict "root" $ "gp" $gp "comp" $gp.components.workspace.codeImage)) }}
{{ end }}

# For backwards compability - remove me soon
{{- define "desktop-ide-images-aliases"}}
{{- $ := .root -}}
{{- $gp := .gp -}}
code-desktop: {{ (include "gitpod.comp.imageFull" (dict "root" $ "gp" $gp "comp" $gp.components.workspace.desktopIdeImages.codeDesktop)) }}
code-desktop-insiders: {{ (include "gitpod.comp.imageFull" (dict "root" $ "gp" $gp "comp" $gp.components.workspace.desktopIdeImages.codeDesktopInsiders)) }}
intellij: {{ (include "gitpod.comp.imageFull" (dict "root" $ "gp" $gp "comp" $gp.components.workspace.desktopIdeImages.intellij)) }}
goland: {{ (include "gitpod.comp.imageFull" (dict "root" $ "gp" $gp "comp" $gp.components.workspace.desktopIdeImages.goland)) }}
{{ end }}

{{- define "ide-preferences" }}
{{- $ := .root -}}
{{- $gp := .gp -}}
sectionTitle: "Default IDE"
sectionSubtitle: "Choose which IDE you want to use."

desktopIdeTitle: "Open in Desktop IDE"
desktopIdeSubtitle: "Choose whether you would like to open your workspace in a desktop IDE instead."
desktopIdeLabel: "Beta"
desktopIdeInfobox: 'While in beta, when you open a workspace using a JetBrains IDE you will need to use the following password: <span class="bg-gray-100 dark:bg-gray-700 px-1.5 py-0.5 rounded-md text-sm font-mono font-medium">gitpod</span>'
desktopIdeFootnote: '<p class="text-left w-full text-gray-500 dark:text-gray-400">The <strong>JetBrains desktop IDEs</strong> are currently in beta. <a href="https://github.com/gitpod-io/gitpod/issues/6576" target="gitpod-feedback-issue" rel="noopener" class="gp-link">Send feedback</a> · <a href="https://www.gitpod.io/docs/integrations/jetbrains" target="_blank" rel="noopener" class="gp-link">Documentation</a></p>'

defaultIde: "code"
defaultDesktopIde: "code-desktop"

options:

  # Browser IDEs
  theia:
    title: "Theia (legacy)"
    tooltip: "This entry exists solely for legacy reasons."
    type: "browser"
    logo: "invalid"
    hidden: true
    image: {{ (include "stable-image-full" (dict "root" $ "gp" $gp "comp" $gp.components.workspace.codeImage)) }}
  code:
    title: "VS Code"
    type: "browser"
    logo: "vscode"
    image: {{ (include "stable-image-full" (dict "root" $ "gp" $gp "comp" $gp.components.workspace.codeImage)) }}
  code-latest:
    title: "VS Code"
    type: "browser"
    logo: "vscode-insiders"
    tooltip: "Early access version, still subject to testing."
    label: "Insiders"
    image: {{ (include "insider-image-full" (dict "root" $ "gp" $gp "comp" $gp.components.workspace.codeImage)) }}
    resolveImageDigest: true

  # Desktop IDEs
  code-desktop:
    title: "VS Code"
    type: "desktop"
    logo: "vscode"
    image: {{ (include "gitpod.comp.imageFull" (dict "root" $ "gp" $gp "comp" $gp.components.workspace.desktopIdeImages.codeDesktop)) }}
  code-desktop-insiders:
    title: "VS Code"
    type: "desktop"
    logo: "vscode-insiders"
    tooltip: "Visual Studio Code Insiders for early adopters."
    label: "Insiders"
    image: {{ (include "gitpod.comp.imageFull" (dict "root" $ "gp" $gp "comp" $gp.components.workspace.desktopIdeImages.codeDesktopInsiders)) }}
  intellij:
    title: "IntelliJ IDEA"
    type: "desktop"
    logo: "intellij-idea"
    tooltip: "IntelliJ IDEA from the Early-Access-Programm (EAP)"
    label: "EAP"
    image: {{ (include "gitpod.comp.imageFull" (dict "root" $ "gp" $gp "comp" $gp.components.workspace.desktopIdeImages.intellij)) }}
  goland:
    title: "GoLand"
    type: "desktop"
    logo: "goland"
    tooltip: "GoLand from the Early-Access-Programm (EAP)"
    label: "EAP"
    image: {{ (include "gitpod.comp.imageFull" (dict "root" $ "gp" $gp "comp" $gp.components.workspace.desktopIdeImages.goland)) }}
{{ end }}

{{- if $comp.serverIdeConfigDeploy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-ide-config
  labels:
    app: {{ template "gitpod.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  # ideVersion, ideImageRepo, ideImageAliases, and desktopIdeImageAliases -- For backwards compability - remove me soon
  config.json: |-
    {
        "ideVersion": "{{ .Values.components.workspace.codeImage.stableVersion }}",
        "ideImageRepo": "{{ template "gitpod.comp.imageRepo" (dict "root" . "gp" $.Values "comp" .Values.components.workspace.codeImage) }}",
        "ideImageAliases": {{ (include "ide-images-aliases" (dict "root" . "gp" $.Values)) | fromYaml | toJson }},
        "desktopIdeImageAliases": {{ (include "desktop-ide-images-aliases" (dict "root" . "gp" $.Values)) | fromYaml | toJson }},

        "supervisorImage": "{{ template "gitpod.comp.imageFull" (dict "root" . "gp" $.Values "comp" .Values.components.workspace.supervisor) }}",
        "idePreferences": {{ (include "ide-preferences" (dict "root" . "gp" $.Values)) | fromYaml | toJson }}
    }
{{- end }}
