{
 "title": "Meta overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Meta cluster",
    "query": {
     "query": "label_values(up{cluster=~\".*meta.*\"}, cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=~\"$cluster\", pod=~\"dashboard.*\"}, node)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=~\"$cluster\", node=~\"$node\", pod=~\"dashboard.*\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (gitpod_version_info{}) by (cluster, gitpod_version)",
     "legendFormat": "{{ cluster }}: {{ gitpod_version }}"
    }
   ]
  },
  {
   "title": "Team slot method calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(gitpod_server_api_calls_user_total{cluster=~\"$cluster\", method=~\"ts.*\"}[5m])) by (cluster, method) * 60",
     "legendFormat": "{{cluster}} {{method}}"
    }
   ]
  },
  {
   "title": "API Request Error ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(gitpod_server_api_calls_total{cluster=~\"$cluster\", pod=~\"$pod\", method=~\"$method\", statusCode!~\"2..|429\"}[5m])\n) by (method)\n/\nsum(\n  rate(gitpod_server_api_calls_total{cluster=~\"$cluster\", pod=~\"$pod\", method=~\"$method\"}[5m])\n) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Websocket connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "server_websocket_connection_count{cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} {{cluster}}"
    }
   ]
  },
  {
   "title": "External metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  },
  {
   "title": "Messagebus health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  }
 ]
}